server:
  port: 8082

spring:
  application:
    name: member-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/loyalty}
    username: ${DB_USER:loyalty}
    password: ${DB_PASSWORD:loyalty}
    hikari:
      maximum-pool-size: 10
  flyway:
    enabled: true
    schemas: loyalty
    default-schema: loyalty
    locations: classpath:db/migration
    validate-on-migrate: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
